### ISSUE TITLE
【課題】221023, 221030

### ISSUE THREAD

**Issue by technicakidz** [dsuke0526/original-app#26]
### 概要

下記機能の完遂を目指した課題．
https://github.com/dsuke0526/original-app/issues/20

### TODOs
- [x] PR https://github.com/dsuke0526/original-app/pull/25 の完了条件を実装ベースで明確にする
   例
   ```
   ### 完了条件
   - [ ] xxx.py の xxx class を修正しこう言った挙動を実現できる 
   ```
- [ ] (余力あれば)ログイン機能 https://github.com/dsuke0526/original-app/issues/2 の実装着手

**Comment by technicakidz** [comment]
各ブランチに master ブランチの状態を更新するコマンド．
エディタの機能でも可能．
```
git pull --rebase origin master
```

**Comment by technicakidz** [comment]
レートごとで画面がゆれてしまうことがわかった．

![five_star](https://user-images.githubusercontent.com/6193750/197370259-bf47db2b-a0dd-42bd-a3af-cf2f34377219.png)

![Two   Half Stars](https://user-images.githubusercontent.com/6193750/197370258-4089b967-74e1-48cf-8e44-b8d7db41a981.png)

**Comment by dsuke0526** [comment]
![スクリーンショット (51)](https://user-images.githubusercontent.com/108209803/197960923-40391b2a-95b1-46d1-849a-6e9839a0aae1.png)
vacode上では値を消してるんですが漫画語ろう！の方に前のまま表示されるんですがなぜか分かりません。

**Comment by dsuke0526** [comment]
今の現状のまとめ
- starretingのトップへの表示は難航しててどうすればいいかもわからない状態
- Googleログイン機能はOauthのIDとキーの取得まで終わっているが実際に表示するまでには至っていない

**Comment by technicakidz** [comment]
### 221030
- [ ]  [アプリのDBに `rating` を追加する](https://github.com/dsuke0526/original-app/pull/25#issuecomment-1296099921)
- [ ]  ログイン機能(google)の表示実装

**Comment by dsuke0526** [comment]
![スクリーンショット (52)](https://user-images.githubusercontent.com/108209803/200107240-0d0b096e-43e5-41e4-bcba-8cdde7702a99.png)
現状
- 追加のやり方は理解できたが、star rating自体の表示には至っていない
わからないこと
- edit.htmlにあるstar ratingをmodels.pyでのクラスの指定をどうしたらいいか
-  view.pyの中身の書き方

**Comment by dsuke0526** [comment]
https://github.com/hellopyplane/Star-ratings-with-Django-and-Javascript

**Comment by technicakidz** [comment]
こちらのコメント
https://github.com/dsuke0526/original-app/pull/25#pullrequestreview-1169401779
の部分でつまずいてしまったため、 star raiting 機能は実装するものの、方針転換して利用ライブラリを変更することに。
